import { Client, Project, Task, Deal, MyCompany, Document, DashboardStats } from './types';

// Mock Data - Datos de ejemplo como en Flutter

export const mockMyCompanies: MyCompany[] = [
  {
    id: '1',
    name: 'Verlyx',
    type: 'technology',
    description: 'Empresa principal de desarrollo de software',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    logoUrl: null,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'PulsarMoon',
    type: 'consulting',
    description: 'Consultoría y desarrollo especializado',
    primaryColor: '#f59e0b',
    secondaryColor: '#d97706',
    logoUrl: null,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Tech Corp',
    type: 'client',
    description: 'Empresa de tecnología líder en el mercado',
    logoUrl: null,
    primaryColor: '#3b82f6',
    secondaryColor: null,
    isActive: true,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Startup Inc',
    type: 'client',
    description: 'Startup innovadora en fintech',
    logoUrl: null,
    primaryColor: '#10b981',
    secondaryColor: null,
    isActive: true,
    createdAt: '2024-07-15T00:00:00Z',
    updatedAt: '2024-07-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Global Services',
    type: 'partner',
    description: 'Socio estratégico de servicios globales',
    logoUrl: null,
    primaryColor: '#8b5cf6',
    secondaryColor: null,
    isActive: true,
    createdAt: '2024-05-20T00:00:00Z',
    updatedAt: '2024-05-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'DataFlow',
    type: 'client',
    description: 'Especialistas en análisis de datos',
    logoUrl: null,
    primaryColor: '#f59e0b',
    secondaryColor: null,
    isActive: true,
    createdAt: '2024-08-10T00:00:00Z',
    updatedAt: '2024-08-10T00:00:00Z',
  },
  {
    id: '5',
    name: 'Cloud Masters',
    type: 'supplier',
    description: 'Proveedor de infraestructura cloud',
    logoUrl: null,
    primaryColor: '#ef4444',
    secondaryColor: null,
    isActive: true,
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2024-04-01T00:00:00Z',
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    myCompanyId: '1',
    clientCompanyId: '1',
    name: 'Plataforma E-commerce',
    description: 'Desarrollo de plataforma de comercio electrónico completa con pagos integrados',
    status: 'in_progress',
    priority: 'high',
    budget: 75000,
    spentAmount: 32000,
    currency: 'USD',
    startDate: '2024-09-01T00:00:00Z',
    dueDate: '2025-03-01T00:00:00Z',
    completionDate: null,
    progressPercentage: 45,
    clientId: '1',
    dealId: null,
    tags: ['ecommerce', 'react', 'nodejs'],
    isArchived: false,
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '2',
    myCompanyId: '1',
    clientCompanyId: '2',
    name: 'App Móvil Fintech',
    description: 'Aplicación móvil para gestión de finanzas personales',
    status: 'planning',
    priority: 'critical',
    budget: 120000,
    spentAmount: 5000,
    currency: 'USD',
    startDate: '2025-02-01T00:00:00Z',
    dueDate: '2025-08-01T00:00:00Z',
    completionDate: null,
    progressPercentage: 10,
    clientId: '2',
    dealId: null,
    tags: ['mobile', 'flutter', 'fintech'],
    isArchived: false,
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '3',
    myCompanyId: '1',
    clientCompanyId: '3',
    name: 'Sistema CRM Personalizado',
    description: 'CRM adaptado a las necesidades específicas del cliente',
    status: 'review',
    priority: 'medium',
    budget: 45000,
    spentAmount: 42000,
    currency: 'USD',
    startDate: '2024-06-01T00:00:00Z',
    dueDate: '2025-01-20T00:00:00Z',
    completionDate: null,
    progressPercentage: 90,
    clientId: '3',
    dealId: null,
    tags: ['crm', 'saas', 'enterprise'],
    isArchived: false,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '4',
    myCompanyId: '2',
    clientCompanyId: '4',
    name: 'Migración Cloud AWS',
    description: 'Migración completa de infraestructura a AWS',
    status: 'in_progress',
    priority: 'high',
    budget: 55000,
    spentAmount: 28000,
    currency: 'USD',
    startDate: '2024-11-01T00:00:00Z',
    dueDate: '2025-04-01T00:00:00Z',
    completionDate: null,
    progressPercentage: 55,
    clientId: '4',
    dealId: null,
    tags: ['aws', 'cloud', 'devops'],
    isArchived: false,
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '5',
    myCompanyId: '1',
    clientCompanyId: '5',
    name: 'Dashboard Analytics',
    description: 'Panel de análisis de datos en tiempo real',
    status: 'done',
    priority: 'medium',
    budget: 30000,
    spentAmount: 28500,
    currency: 'USD',
    startDate: '2024-03-01T00:00:00Z',
    dueDate: '2024-09-01T00:00:00Z',
    completionDate: '2024-08-25T00:00:00Z',
    progressPercentage: 100,
    clientId: '5',
    dealId: null,
    tags: ['analytics', 'dashboard', 'bi'],
    isArchived: false,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-08-25T00:00:00Z',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    myCompanyId: '1',
    projectId: '1',
    dealId: null,
    clientId: null,
    parentTaskId: null,
    title: 'Diseñar mockups del checkout',
    description: 'Crear diseños de alta fidelidad para el flujo de checkout',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: 'user1',
    startDate: '2025-01-10T00:00:00Z',
    dueDate: '2025-01-18T00:00:00Z',
    completedAt: null,
    estimatedHours: 16,
    actualHours: 8,
    progressPercentage: 50,
    isBlocked: false,
    blockedReason: null,
    tags: ['design', 'ux'],
    checklist: [
      { text: 'Wireframes', completed: true, order: 0 },
      { text: 'Mockups desktop', completed: true, order: 1 },
      { text: 'Mockups mobile', completed: false, order: 2 },
      { text: 'Prototipo interactivo', completed: false, order: 3 },
    ],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '2',
    myCompanyId: '1',
    projectId: '1',
    dealId: null,
    clientId: null,
    parentTaskId: null,
    title: 'Implementar pasarela de pagos',
    description: 'Integrar Stripe para procesamiento de pagos',
    status: 'TODO',
    priority: 'CRITICAL',
    assignedTo: 'user2',
    startDate: '2025-01-20T00:00:00Z',
    dueDate: '2025-02-05T00:00:00Z',
    completedAt: null,
    estimatedHours: 40,
    actualHours: 0,
    progressPercentage: 0,
    isBlocked: false,
    blockedReason: null,
    tags: ['backend', 'payments'],
    checklist: [],
    createdAt: '2025-01-12T00:00:00Z',
    updatedAt: '2025-01-12T00:00:00Z',
  },
  {
    id: '3',
    myCompanyId: '1',
    projectId: '2',
    dealId: null,
    clientId: null,
    parentTaskId: null,
    title: 'Definir arquitectura de la app',
    description: 'Documentar la arquitectura técnica de la aplicación Flutter',
    status: 'REVIEW',
    priority: 'HIGH',
    assignedTo: 'user1',
    startDate: '2025-01-08T00:00:00Z',
    dueDate: '2025-01-15T00:00:00Z',
    completedAt: null,
    estimatedHours: 24,
    actualHours: 20,
    progressPercentage: 85,
    isBlocked: false,
    blockedReason: null,
    tags: ['architecture', 'documentation'],
    checklist: [
      { text: 'Diagrama de componentes', completed: true, order: 0 },
      { text: 'Flujo de datos', completed: true, order: 1 },
      { text: 'Documentación API', completed: false, order: 2 },
    ],
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '4',
    myCompanyId: '1',
    projectId: '3',
    dealId: null,
    clientId: null,
    parentTaskId: null,
    title: 'Corregir bugs reportados',
    description: 'Resolver los 5 bugs críticos reportados por QA',
    status: 'BLOCKED',
    priority: 'HIGH',
    assignedTo: 'user3',
    startDate: '2025-01-13T00:00:00Z',
    dueDate: '2025-01-16T00:00:00Z',
    completedAt: null,
    estimatedHours: 12,
    actualHours: 4,
    progressPercentage: 30,
    isBlocked: true,
    blockedReason: 'Esperando acceso al servidor de producción',
    tags: ['bugfix', 'qa'],
    checklist: [],
    createdAt: '2025-01-13T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '5',
    myCompanyId: '1',
    projectId: '1',
    dealId: null,
    clientId: null,
    parentTaskId: null,
    title: 'Configurar CI/CD',
    description: 'Implementar pipeline de integración continua con GitHub Actions',
    status: 'DONE',
    priority: 'MEDIUM',
    assignedTo: 'user2',
    startDate: '2025-01-05T00:00:00Z',
    dueDate: '2025-01-10T00:00:00Z',
    completedAt: '2025-01-09T00:00:00Z',
    estimatedHours: 8,
    actualHours: 6,
    progressPercentage: 100,
    isBlocked: false,
    blockedReason: null,
    tags: ['devops', 'ci-cd'],
    checklist: [],
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-09T00:00:00Z',
  },
  {
    id: '6',
    myCompanyId: '1',
    projectId: '4',
    dealId: null,
    clientId: null,
    parentTaskId: null,
    title: 'Migrar base de datos RDS',
    description: 'Migrar PostgreSQL on-premise a Amazon RDS',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    assignedTo: 'user1',
    startDate: '2025-01-10T00:00:00Z',
    dueDate: '2025-01-25T00:00:00Z',
    completedAt: null,
    estimatedHours: 32,
    actualHours: 12,
    progressPercentage: 40,
    isBlocked: false,
    blockedReason: null,
    tags: ['database', 'aws', 'migration'],
    checklist: [
      { text: 'Backup completo', completed: true, order: 0 },
      { text: 'Crear instancia RDS', completed: true, order: 1 },
      { text: 'Migrar datos', completed: false, order: 2 },
      { text: 'Verificar integridad', completed: false, order: 3 },
      { text: 'Cambiar conexiones', completed: false, order: 4 },
    ],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
];

export const mockDeals: Deal[] = [
  {
    id: '1',
    myCompanyId: '1',
    clientId: '1',
    organizationId: null,
    title: 'Implementación Sistema ERP',
    description: 'Sistema ERP completo para gestión empresarial',
    stage: 'NEGOTIATION',
    priority: 'HIGH',
    amount: 85000,
    currency: 'USD',
    probability: 75,
    expectedRevenue: 63750,
    expectedCloseDate: '2025-02-15T00:00:00Z',
    actualCloseDate: null,
    lostReason: null,
    wonReason: null,
    source: 'Referido',
    daysInStage: 5,
    nextAction: 'Enviar propuesta final',
    nextActionDate: '2025-01-16T00:00:00Z',
    isActive: true,
    createdAt: '2024-12-01T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '2',
    myCompanyId: '1',
    clientId: '2',
    organizationId: null,
    title: 'Consultoría Transformación Digital',
    description: 'Asesoría para proceso de transformación digital',
    stage: 'PROPOSAL',
    priority: 'MEDIUM',
    amount: 35000,
    currency: 'USD',
    probability: 50,
    expectedRevenue: 17500,
    expectedCloseDate: '2025-03-01T00:00:00Z',
    actualCloseDate: null,
    lostReason: null,
    wonReason: null,
    source: 'LinkedIn',
    daysInStage: 3,
    nextAction: 'Agendar demo',
    nextActionDate: '2025-01-17T00:00:00Z',
    isActive: true,
    createdAt: '2024-12-15T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '3',
    myCompanyId: '1',
    clientId: '3',
    organizationId: null,
    title: 'Desarrollo App Móvil',
    description: 'Aplicación móvil para gestión de inventario',
    stage: 'QUALIFIED',
    priority: 'HIGH',
    amount: 55000,
    currency: 'USD',
    probability: 40,
    expectedRevenue: 22000,
    expectedCloseDate: '2025-04-01T00:00:00Z',
    actualCloseDate: null,
    lostReason: null,
    wonReason: null,
    source: 'Sitio Web',
    daysInStage: 7,
    nextAction: 'Llamada de descubrimiento',
    nextActionDate: '2025-01-18T00:00:00Z',
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '4',
    myCompanyId: '1',
    clientId: '4',
    organizationId: null,
    title: 'Migración a la Nube',
    description: 'Migración completa de infraestructura on-premise a cloud',
    stage: 'LEAD',
    priority: 'MEDIUM',
    amount: 45000,
    currency: 'USD',
    probability: 20,
    expectedRevenue: 9000,
    expectedCloseDate: '2025-05-01T00:00:00Z',
    actualCloseDate: null,
    lostReason: null,
    wonReason: null,
    source: 'Evento',
    daysInStage: 2,
    nextAction: 'Enviar información',
    nextActionDate: '2025-01-15T00:00:00Z',
    isActive: true,
    createdAt: '2025-01-12T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: '5',
    myCompanyId: '1',
    clientId: '5',
    organizationId: null,
    title: 'Integración API Terceros',
    description: 'Integración con múltiples APIs de terceros',
    stage: 'CLOSED_WON',
    priority: 'HIGH',
    amount: 28000,
    currency: 'USD',
    probability: 100,
    expectedRevenue: 28000,
    expectedCloseDate: '2025-01-10T00:00:00Z',
    actualCloseDate: '2025-01-08T00:00:00Z',
    lostReason: null,
    wonReason: 'Precio competitivo y experiencia previa',
    source: 'Referido',
    daysInStage: 6,
    nextAction: null,
    nextActionDate: null,
    isActive: false,
    createdAt: '2024-11-20T00:00:00Z',
    updatedAt: '2025-01-08T00:00:00Z',
  },
  {
    id: '6',
    myCompanyId: '1',
    clientId: '1',
    organizationId: null,
    title: 'Rediseño Portal Web',
    description: 'Rediseño completo del portal corporativo',
    stage: 'CLOSED_LOST',
    priority: 'LOW',
    amount: 22000,
    currency: 'USD',
    probability: 0,
    expectedRevenue: 0,
    expectedCloseDate: '2025-01-05T00:00:00Z',
    actualCloseDate: '2025-01-03T00:00:00Z',
    lostReason: 'Eligieron competidor por precio',
    wonReason: null,
    source: 'Email',
    daysInStage: 11,
    nextAction: null,
    nextActionDate: null,
    isActive: false,
    createdAt: '2024-10-15T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
];

export const mockDocuments: Document[] = [
  {
    id: '1',
    name: 'Propuesta Comercial - Tech Corp.pdf',
    filePath: '/documents/propuesta-tech-corp.pdf',
    description: 'Propuesta comercial para proyecto E-commerce',
    folder: 'Propuestas',
    mimeType: 'application/pdf',
    size: 2457600,
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'Contrato de Servicios.pdf',
    filePath: '/documents/contrato-servicios.pdf',
    description: 'Contrato marco de servicios',
    folder: 'Contratos',
    mimeType: 'application/pdf',
    size: 1843200,
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-08T00:00:00Z',
  },
  {
    id: '3',
    name: 'Logo Cliente.png',
    filePath: '/documents/logo-cliente.png',
    description: 'Logo del cliente en alta resolución',
    folder: 'Imágenes',
    mimeType: 'image/png',
    size: 460800,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
  },
  {
    id: '4',
    name: 'Presupuesto Q1 2025.xlsx',
    filePath: '/documents/presupuesto-q1-2025.xlsx',
    description: 'Presupuesto del primer trimestre',
    folder: 'Finanzas',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 911360,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
  },
  {
    id: '5',
    name: 'Manual de Usuario v2.docx',
    filePath: '/documents/manual-usuario-v2.docx',
    description: 'Manual de usuario del sistema CRM',
    folder: 'Documentación',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 3276800,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-12T00:00:00Z',
  },
];

export const getDashboardStats = (): DashboardStats => {
  return {
    projectsTotal: mockProjects.length,
    projectsInProgress: mockProjects.filter(p => p.status === 'in_progress').length,
    tasksTotal: mockTasks.length,
    tasksPending: mockTasks.filter(t => t.status === 'TODO' || t.status === 'IN_PROGRESS').length,
    dealsTotal: mockDeals.filter(d => d.isActive).length,
    dealsValue: mockDeals.filter(d => d.isActive).reduce((sum, d) => sum + (d.amount || 0), 0),
    clientsTotal: mockClients.length,
  };
};
